name: package smoke

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Run package smoke action
        uses: spearzy/dotnet-package-smoke@v1
        with:
          package-projects: |
            src/MyLibrary/MyLibrary.csproj
            src/MyLibrary.Extensions/MyLibrary.Extensions.csproj
          consumer-mode: per-package
